### ISSUE TITLE
Problems migrating from 1.0.0 to 2.0.0

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#264]
I had a subproject that used this plugin called `myproject`.

I've done so:

```
enablePlugins(JettyPlugin)
```

But I cannot use expressions like:

``` scala
   myTask := {
      start in (myproject, Jetty).value
      ....
   }
```

Previously, I could use:

``` scala
   myTask := {
      start in (myproject, container).value
      ....
   }
```

How can I now activate this plugin in a subproject?

**Comment by earldouglas** [comment]
I think you just need to import `start` -- it's not among the auto-imported fields in [`ContainerPlugin`](https://github.com/earldouglas/xsbt-web-plugin/blob/2.0.0/src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala#L9):

```scala
myTask := {
  import ContainerPlugin.start
  (start in (myproject, Jetty)).value
}
```

**Comment by DavidPerezIngeniero** [comment]
Thanks for your suggestion.  Now I'm dealing with more urgent issues.  I'll check this later.

**Comment by earldouglas** [comment]
Any luck getting this to work in 2.0?

**Comment by DavidPerezIngeniero** [comment]
Thanks for your interest Earl.  Now it compiles, but I'm having that the stop task isn't recognized:

```scala
import ContainerPlugin.stop
val end = taskKey[Unit]("End")
end := (stop in (servision, Jetty)).value
```

**Comment by earldouglas** [comment]
What do you mean by "isn't recognized"?  Does the task fail when you call it from sbt?

The following works for me when I add it to a simple project like [xwp-template](https://github.com/earldouglas/xwp-template):

*build.sbt:*

```scala
val servision = (project in file("."))

val begin = taskKey[Unit]("Begin")

begin := (ContainerPlugin.start in (servision, Jetty)).value

val end = taskKey[Unit]("End")

end := (ContainerPlugin.stop in (servision, Jetty)).value
```

**Comment by DavidPerezIngeniero** [comment]
I get this error:

```
        at sbt.Init$class.Uninitialized(Settings.scala:270)
        at sbt.Def$.Uninitialized(Def.scala:10)
        at sbt.Init$class.delegate(Settings.scala:191)
        at sbt.Def$.delegate(Def.scala:10)
        at sbt.Init$class.compiled(Settings.scala:138)
        at sbt.Def$.compiled(Def.scala:10)
        at sbt.Init$class.make(Settings.scala:144)
        at sbt.Def$.make(Def.scala:10)
        at sbt.Load$.apply(Load.scala:135)
        at sbt.Load$.defaultLoad(Load.scala:36)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
        at sbt.Command$.process(Command.scala:92)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:98)
        at sbt.MainLoop$.run(MainLoop.scala:91)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
[error] Reference to undefined setting: 

[error]   servision/jetty:stop from rds/*:fin (/home/d/rds/build.sbt:251)
```

when using version 2.0.4 with SBT 0.13.8, and the above code.

**Comment by earldouglas** [comment]
Does */home/d/rds/build.sbt* include a line enabling the `JettyPlugin`?

If you don't define `end := ...`, can you define `begin := ...` without the same error?

**Comment by earldouglas** [comment]
Closing since there hasn't been any activity on this thread in well over a year.  Feel free to re-open if you're still encountering this problem.
