### ISSUE TITLE
NumberFormatException when use milestone or RC version sbt

### ISSUE THREAD

**Issue by xuwei-k** [earldouglas/xsbt-web-plugin#342]
https://github.com/earldouglas/xsbt-web-plugin/blob/3.0.2/src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala#L155

build.properties

```
sbt.version=0.13.16-M1
```

stack trace

```
java.lang.NumberFormatException: For input string: "16-M1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
	at com.earldouglas.xwp.ContainerPlugin$$anonfun$6.apply(ContainerPlugin.scala:152)
	at com.earldouglas.xwp.ContainerPlugin$$anonfun$6.apply(ContainerPlugin.scala:152)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:108)
	at com.earldouglas.xwp.ContainerPlugin$.com$earldouglas$xwp$ContainerPlugin$$validateSbtVerison(ContainerPlugin.scala:152)
	at com.earldouglas.xwp.ContainerPlugin$$anonfun$onLoadSetting$1$$anonfun$apply$6.apply(ContainerPlugin.scala:170)
	at com.earldouglas.xwp.ContainerPlugin$$anonfun$onLoadSetting$1$$anonfun$apply$6.apply(ContainerPlugin.scala:169)
```

**Comment by earldouglas** [comment]
The fix for this is available in version 3.0.3.
